// allheaders.h
#pragma once

#include <iostream>
#include <vector>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <stack>
#include <deque>
#include <list>
#include <string>
#include <algorithm>
#include <cmath>
#include <numeric>
#include <functional>
#include <bitset>
#include <tuple>
#include <sstream>
#include <iomanip>
#include <limits>
#include <cassert>
#include <climits>
#include <cctype>
#include <cstring>
#include <fstream>
